[[simulation]]
name = "FMO"
method = "HEOM"
output = "test.hdf5"

nsteps = 1000
dt = 1.0
Lmax = 3
num_modes = 2
threshold = 1e-10

outgroup = "init1"
observable_output = "dt_1.0_Lmax3_nmodes_2.dat"

[[simulation.observable]]
observable = "P_1"
[[simulation.observable]]
observable = "P_2"
[[simulation.observable]]
observable = "P_3"
[[simulation.observable]]
observable = "P_4"
[[simulation.observable]]
observable = "P_5"
[[simulation.observable]]
observable = "P_6"
[[simulation.observable]]
observable = "P_7"
[[simulation.observable]]
observable = "trace"
[[simulation.observable]]
observable = "purity"
[[simulation.observable]]
observable = "vonNeumann_entropy"

[[simulation]]
name = "FMO"
method = "HEOM"
output = "test.hdf5"

nsteps = 1000
dt = 1.0
Lmax = 4
num_modes = 4
threshold = 1e-10

outgroup = "init1"
observable_output = "dt_1.0_Lmax4_nmodes_4.dat"

[[simulation.observable]]
observable = "P_1"
[[simulation.observable]]
observable = "P_2"
[[simulation.observable]]
observable = "P_3"
[[simulation.observable]]
observable = "P_4"
[[simulation.observable]]
observable = "P_5"
[[simulation.observable]]
observable = "P_6"
[[simulation.observable]]
observable = "P_7"
[[simulation.observable]]
observable = "trace"
[[simulation.observable]]
observable = "purity"
[[simulation.observable]]
observable = "vonNeumann_entropy"
